#!/bin/sh
set -u

SOURCE=${WATTLINE_NGINX_SOURCE:-/etc/nginx/conf.d/gl-app-wattline.locations}
LINK=${WATTLINE_NGINX_LINK:-${IPKG_INSTROOT:-}/etc/nginx/gl-conf.d/gl-app-wattline.conf}
NGINX=${WATTLINE_NGINX_BIN:-/usr/sbin/nginx}
NGINX_INIT=${WATTLINE_NGINX_INIT:-}

[ -L "$LINK" ] || exit 0
[ "$(readlink "$LINK")" = "$SOURCE" ] || exit 0
rm -f "$LINK" || exit 1

[ -n "${IPKG_INSTROOT:-}" ] && exit 0

if ! "$NGINX" -t; then
	ln -s "$SOURCE" "$LINK"
	echo 'gl-app-wattline: nginx validation failed; proxy removal was rolled back' >&2
	exit 1
fi

if [ -n "$NGINX_INIT" ]; then
	"$NGINX_INIT" reload
else
	"$NGINX" -s reload
fi
